server:
  port: 8080

spring:
  profiles:
    include: prod
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    async:
      request-timeout: 60000

DSRestConnection:
  HTTP:
    ConnectTimeout: 6000;

log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator

logging:
  config: classpath:logback.xml

operation:
  type: JPA